version: '2'
services:
  formica:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
